# Generated by Django 2.2.24 on 2021-12-03 10:41

from django.db import migrations
import phonenumbers


def feelup_purephone_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parsing_phone_num = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsing_phone_num):
            flat.owner_pure_phone = parsing_phone_num
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20211203_1129'),
    ]

    operations = [migrations.RunPython(feelup_purephone_fields)]

