# Generated by Django 2.2.24 on 2021-12-03 12:26

from django.db import migrations


def fillup_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner_full_name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone)




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20211203_1525'),
    ]

    operations = [migrations.RunPython(fillup_owner_model)
    ]
