# Generated by Django 2.2.24 on 2021-12-05 11:15

from django.db import migrations


def fill_all_fields(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flat = Flat.objects.get(
            owner=owner.owner_full_name,
            owners_phonenumber=owner.owners_phonenumber,
            owner_pure_phone=owner.owner_pure_phone
        )
        owner.ownners_flats.add(flat)
        owner.save()



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20211203_1526'),
    ]

    operations = [migrations.RunPython(fill_all_fields)
    ]
